#pragma once

#include "config.h"
#include "Ganymede/Source/Ganymede.h"

class IoSurface;
class EuropaSemaphore;
class EuropaFence;
struct EuropaSurfaceCapabilities;
struct EuropaSurfaceFormat;
struct EuropaSwapChainCapabilities;
class EuropaSurface;
struct EuropaQueueFamilyProperties;
struct EuropaSwapChainCreateInfo;
class EuropaSwapChain;
class EuropaQueue;
struct EuropaImageInfo;
class EuropaImage;
struct EuropaImageViewCreateInfo;
class EuropaImageView;
class EuropaShaderModule;
struct EuropaShaderStageInfo;
struct EuropaVertexInputBindingInfo;
struct EuropaVertexAttributeBindingInfo;
struct EuropaVertexInputStageInfo;
struct EuropaInputAssemblyStageInfo;
struct EuropaViewport;
struct EuropaScissor;
struct EuropaPipelineViewportStateInfo;
struct EuropaRasterizerStateInfo;
struct EuropaDepthStencilStateInfo;
class EuropaDescriptorSetLayout;
struct EuropaPipelineLayoutInfo;
class EuropaPipelineLayout;
struct EuropaAttachmentInfo;
struct EuropaAttachmentReference;
class EuropaRenderPass;
struct EuropaBufferInfo;
class EuropaBuffer;
class EuropaBufferView;
struct EuropaGraphicsPipelineCreateInfo;
class EuropaPipeline;
struct EuropaFramebufferCreateInfo;
class EuropaFramebuffer;
class EuropaDescriptorSet;
class EuropaCmdlist;
struct EuropaDescriptorPoolSizes;
class EuropaDescriptorPool;
class EuropaCommandPool;
class EuropaDevice;
class Europa;
